force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Price_per_Participant__c.field-meta.xml
<CustomField>
    <fullName>Price_per_Participant__c</fullName>
    <label>Price per Participant</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WebinarController.cls
/**
 * Created by mgieron on 13.07.2022.
 */

public with sharing class WebinarController {
    @AuraEnabled
    public static Id createWebinar(String name, String type, String cost, String price) {
        Webinar__c webinar = new Webinar__c(
                Name = name,
                Type__c = type,
                Cost__c = Integer.valueOf(cost),
                Price_per_Participant__c = Integer.valueOf(price));
        insert webinar;
        return webinar.Id;
    }

    @AuraEnabled
    public static String getLatestQuestionnaire(String webinarId){
        return [SELECT Id FROM Questionnaire__c WHERE Webinar__c=:webinarId ORDER BY CreatedDate DESC LIMIT 1].Id;
    }
}