force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Number_of_Participants__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Participants__c</fullName>
    <label>Number of Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Price_per_Participant__c.field-meta.xml
<CustomField>
    <fullName>Price_per_Participant__c</fullName>
    <label>Price per Participant</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Registration Open</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webinar__c/fields/Total_Number_of_Seats__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Seats__c</fullName>
    <label>Total Number of Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WebinarTriggerHandler.cls
/**
 * Created by mgieron on 06.07.2022.
 */

public with sharing class WebinarTriggerHandler {
    public static void handleBeforeInsert(List<Webinar__c> newWebinars) {
        for (Webinar__c webinar : newWebinars) {
            beforeInsertOrUpdateOperations(webinar);
        }
    }

    public static void handleBeforeUpdate(List<Webinar__c> newWebinars) {
        for (Webinar__c webinar : newWebinars) {
            beforeInsertOrUpdateOperations(webinar);
        }
    }

    private static void beforeInsertOrUpdateOperations(Webinar__c webinar) {
        if (isNumberOfParticipantsExceedingSeatNumber(webinar)) webinar.addError('Number of participants exceeds...');
        if (isCostBelow100Euro(webinar)) approveWebinar(webinar);
        if (isRejected(webinar)) cancel(webinar);
        if (!canStatusBePending(webinar) && isStatusPending(webinar)) webinar.addError('Status cannot be pending');
        updatePricePerParticipant(webinar);
    }

    private static Boolean isCostBelow100Euro(Webinar__c webinar) {
        return webinar.Cost__c < 100;
    }

    private static void approveWebinar(Webinar__c webinar) {
        webinar.Approval_Status__c = 'Approved';
    }

    private static Boolean isCancelled(Webinar__c webinar) {
        return webinar.Status__c == 'Canceled';
    }

    private static void rejectWebinar(Webinar__c webinar) {
        webinar.Approval_Status__c = 'Rejected';
    }

    private static void updatePricePerParticipant(Webinar__c webinar) {
        if (webinar.Cost__c == null || webinar.Number_of_Participants__c == null || webinar.Number_of_Participants__c == 0) {
            webinar.Price_per_Participant__c = 0;
        } else {
            webinar.Price_per_Participant__c = webinar.Cost__c / webinar.Number_of_Participants__c;
        }
    }

    private static Boolean isStatusPending(Webinar__c webinar) {
        return webinar.Approval_Status__c == 'Pending';
    }

    private static Boolean canStatusBePending(Webinar__c webinar) {
        return webinar.Status__c == 'New' || webinar.Status__c == 'Canceled';
    }

    private static Boolean isRejected(Webinar__c webinar) {
        return webinar.Approval_Status__c == 'Rejected';
    }

    private static void cancel(Webinar__c webinar) {
        webinar.Status__c = 'Canceled';
    }

    private static Boolean isNumberOfParticipantsExceedingSeatNumber(Webinar__c webinar) {
        return webinar.Number_of_Participants__c != null &&
                webinar.Total_Number_of_Seats__c != null &&
                (webinar.Number_of_Participants__c > webinar.Total_Number_of_Seats__c);
    }

    public static void handleAfterInsert(List<Webinar__c> webinars) {
        List<WebinarEvent__e> events = new List<WebinarEvent__e>();
        for (Webinar__c webinar : webinars) {
            events.add(new WebinarEvent__e());
        }
        EventBus.publish(events);
    }
}