force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar_Team_Member__c/Webinar_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Webinar Team Member</label>
    <nameField>
        <label>Webinar Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinar Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar_Team_Member__c/fields/Related_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Related_Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Webinar</label>
    <referenceTo>Webinar__c</referenceTo>
    <relationshipLabel>Webinar Team Members</relationshipLabel>
    <relationshipName>Webinar_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AutoNotifications.cls
/**
 * Created by mgieron on 14.07.2022.
 */

public with sharing class AutoNotifications implements Schedulable {

    public void execute(SchedulableContext schedulableContext) {
        List<Webinar__c> webinars = getWebinars();

        for (Webinar__c webinar : webinars) {
            ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), webinar.Id, ConnectApi.FeedElementType.FeedItem, webinar.Name + ' starts soon!');
        }
    }

    private List<Webinar__c> getWebinars() {
        Datetime current = Datetime.now();
        Datetime inTwoHours = Datetime.now().addHours(2);

        return [
                SELECT Id, Name, (SELECT Id FROM Webinar_Team_Members__r)
                FROM Webinar__c
                WHERE Start_Date__c >= :current AND Start_Date__c <= :inTwoHours
        ];
    }
}